# canais.yaml
canais:
  - nome: FizzQuirkTikTok
    plataforma: TikTok
    logo: background.png
    hashtags: ["Educação", "Curiosidades"]

  - nome: FizzQuirkYouTube
    plataforma: YouTube
    youtube_channel_id: UCWeFg_QABGRseHXFV7YdrVw
    logo: background.png
    hashtags: ["OutroCanal", "Educação", "Curiosidades"]
